{"name": "test_prosumer_operating", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './tests/tests/config.json'", "trace": "@pytest.fixture(scope=\"session\")\n    def driver():\n>       locale = str(config_importer.config_locale())\n\ntests/conftest.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nhelpers/config_importer.py:67: in config_locale\n    config = self.config()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <helpers.config_importer.ConfigImporter object at 0x10fd8fb20>\n\n    def config(self):\n>       with open(self.CONFIG_PATH, 'r') as config_file:\nE       FileNotFoundError: [Errno 2] No such file or directory: './tests/tests/config.json'\n\nhelpers/config_importer.py:12: FileNotFoundError"}, "start": 1679900725326, "stop": 1679900725326, "uuid": "ac35949c-1ca8-4863-94f3-0b831ddeefd6", "historyId": "d2bfca0662e2bf13018ba0a7b6a98367", "testCaseId": "61c927cf27a61dcc290ca9ed65572f60", "fullName": "tests.tests.test_dashboard_prosumer.TestProsumer#test_prosumer_operating", "labels": [{"name": "tag", "value": "prosumer_operating"}, {"name": "parentSuite", "value": "tests.tests"}, {"name": "suite", "value": "test_dashboard_prosumer"}, {"name": "subSuite", "value": "TestProsumer"}, {"name": "host", "value": "ypetryk-MacBook-Pro.local"}, {"name": "thread", "value": "2045-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests.test_dashboard_prosumer"}]}