{"uuid": "d95bf34f-e2e9-41dd-8917-a27929b6a657", "children": ["ac35949c-1ca8-4863-94f3-0b831ddeefd6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './tests/tests/config.json'\n", "trace": "  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/tests/conftest.py\", line 10, in driver\n    locale = str(config_importer.config_locale())\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/helpers/config_importer.py\", line 67, in config_locale\n    config = self.config()\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-ios/tests/helpers/config_importer.py\", line 12, in config\n    with open(self.CONFIG_PATH, 'r') as config_file:\n"}, "start": 1679900725418, "stop": 1679900725418}], "start": 1679900725418, "stop": 1679900725502}